AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description: Regional CodePipeline resources required for Cloudprem pipelines

Metadata:

  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Required Configuration
      Parameters:
      - OwnerName

Parameters:

  SourceActionVersion:
    Type: String
    Description: Version of the custom source action for CodePipeline. Update the version if required
    Default: '1'

  SourceActionProvider:
    Type: String
    Description: Provider name of the custom source action for CodePipeline
    Default: Git

  OwnerName:
    Type: String
    Description: An arbitrary tag name for the owner of the environment pipeline

  CodeCommit:
    Type: String
    AllowedValues: [true, false]
    Default: False
    Description: Create a local code commit repository for regional configuration, we will seed the repository's `master` branch with the default config.

  CodeCommitBucket:
    Type: String
    Default: dozuki-cloudprem-assets
    Description: If creating CodeCommit repository, what S3 bucket has the seed zip file.

  CodeCommitObject:
    Type: String
    Default: cloudprem-config.zip
    Description: The object in the bucket listed above to seed the repository with.

  CodeCommitVersion:
    Type: String
    Default: latest
    Description: Which version of the seed zip should we use.

Conditions:

    CreateCodeCommit: !Equals [ !Ref CodeCommit, 'true' ]
    UseLatestSeed: !Equals [ !Ref CodeCommitVersion, latest ]

Mappings:

  PartitionMap: 
    aws:
      ServerlessRepoArn: arn:aws:serverlessrepo:us-east-1:010601635461:applications/dozuki-codepipeline
    aws-us-gov:
      ServerlessRepoArn: arn:aws-us-gov:serverlessrepo:us-gov-west-1:446787640263:applications/dozuki-codepipeline

Resources:

  DozukiCodepipeline:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: !FindInMap [ PartitionMap, !Ref "AWS::Partition", ServerlessRepoArn]
        SemanticVersion: 1.2.0
      Parameters:
        SourceActionVersion: !Ref SourceActionVersion
        SourceActionProvider: !Ref SourceActionProvider
        OwnerName: !Ref OwnerName

  LocalConfig:
    Type: AWS::CodeCommit::Repository
    Condition: CreateCodeCommit
    Properties:
      RepositoryName: !Sub dozuki-config-${AWS::Region}
      RepositoryDescription: Infrastructure configuration for stacks in this region.
      Code:
        BranchName: master
        S3:
          Bucket: !Ref CodeCommitBucket
          Key: !Ref CodeCommitObject
          ObjectVersion: !If [ UseLatestSeed , !Ref AWS::NoValue, !Ref CodeCommitVersion ]

Outputs:

  PublicSSHKey:
    Description: Public SSH key for the Git CodePipeline source stage. Add the SSH key to your git repository
    Value: !GetAtt DozukiCodepipeline.Outputs.PublicSSHKey

  BucketName:
    Description: Codepipeline artifcats S3 bucket name
    Value: !GetAtt DozukiCodepipeline.Outputs.BucketName

  BucketArn:
    Description: Codepipeline artifcats S3 bucket ARN
    Value: !GetAtt DozukiCodepipeline.Outputs.BucketArn

  CodeCommitRepoName:
    Condition: CreateCodeCommit
    Description: CodeCommit repository name for regional infra configuration.
    Export:
        Name: code-commit-repo-name
    Value: !GetAtt LocalConfig.Name